version: '3.8'
services:
  finnplaylogin-app:
    image: finnplaylogin
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://finnplaylogin-mysql:3306/finnplaylogin?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - APP_SLEEP=10
    ports:
      - 127.0.0.1:8080:8080
  finnplaylogin-mysql:
    image: mysql:8.0.30
    # volumes:                                                                   
    #   - ~/volumes/app/FinnplayLogin/mysql/:/var/lib/mysql/
    volumes:
      - ./config/mysql:/etc/mysql/conf.dl
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=finnplaylogin
    ports:
      - 127.0.0.1:3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
